### PR TITLE
description file for developing workflow added

### PR DESCRIPTION
**Pull request by koojozsef**
Added a minimal workflow for project, just trying to prevent a total mess.

### CODE REVIEW

**Comment by Jugis** [comment]
*prevent a TOTAL mess.
Btw look at the GIT pro preaching the wisdom of the GIT bible 🥇 🥇 👍

**Comment by koojozsef** [comment]
comment corrected, please add an approved review

**Comment by Jugis** [comment]
Is a heart and a like enough for an "approved review"?

**Review by Jugis — APPROVED** [review]
BreadHeaded Cat approves.

**Comment by Jugis** [comment]
Btw is this workflow something that is generated, does this also imply rules that must be obeyed? How does this even work? I do not presume this is  just something that you wrote by hand.

**Pull request merged**
